<Project>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>$(WarningsAsErrors);CS1591</WarningsAsErrors>
		<AnalysisLevel>latest</AnalysisLevel>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<Company>YourCompany</Company>
		<Authors>YourTeam</Authors>
		<Copyright>Copyright © $(Company) $(Date:yyyy)</Copyright>
		<RepositoryUrl>https://github.com/606/aws</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="8.0.0" PrivateAssets="all" />
		<PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.435" PrivateAssets="all" />
	</ItemGroup>
</Project>
