<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Se.Aws.Shared.Helpers</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="Amazon.Lambda.Core" Version="2.7.0" />
      <PackageReference Include="AWSSDK.CloudWatchLogs" Version="3.*" />
    </ItemGroup>
</Project>
