<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Se.Aws.Cost.Guard.Lambda</RootNamespace>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>
  <ItemGroup>
  <PackageReference Include="Amazon.Lambda.Core" Version="2.7.0" />
  <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
  <PackageReference Include="AWSSDK.EC2" Version="3.*" />
  <PackageReference Include="AWSSDK.ElasticLoadBalancing" Version="3.*" />
  <PackageReference Include="AWSSDK.ElasticLoadBalancingV2" Version="3.*" />
  <PackageReference Include="AWSSDK.CloudWatchLogs" Version="3.*" />
  <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
  </ItemGroup>
  <ItemGroup>
  <ProjectReference Include="../../../../libs/Se.Aws.Shared.Helpers/Se.Aws.Shared.Helpers.csproj" />
  </ItemGroup>
</Project>
